os: linux
dist: xenial
language: python
cache:
  directories:
    - eggs
    - downloads
python: 2.7
jobs:
  include:
    - python: "2.7"
      env: PLONE_VERSION=4.3
    - python: "3.7"
      env: PLONE_VERSION=5.2
  fast_finish: true
before_install:
  - pip install -r requirements.txt
  - cp plone-$PLONE_VERSION.x.cfg buildout.cfg
install:
  - buildout -N buildout:download-cache=downloads annotate
  - buildout -t 30 buildout:download-cache=downloads
script:
  - bin/test

notifications:
  email:
    recipients:
      - devel@lists.affinitic.be
      - devs@imio.be
    on_success: change
    on_failure: change
